#role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-deployer
rules:
- apiGroups:
   - ""
   - extensions
   - apps
  resources:
    - configmaps
    - deployments
    - endpoints
    - horizontalpodautoscalers
    - ingresses
    - jobs
    - pods
    - persistentvolumes
    - persistentvolumeclaims
    - replicasets
    - serviceaccounts
    - services
    - statefulsets
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups:
    - ""
  resources:
  - secrets
  verbs: ["create", "update", "patch"]  

#role binding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-deployer
subjects:
- kind: ServiceAccount
  name: app-deployer
  namespace: jpw

#service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-deployer
  namespace: jpw