#role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: image-setter
rules:
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - update
  - patch
  - get

#role binding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-setter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: image-setter
subjects:
- kind: ServiceAccount
  name: image-setter
  namespace: jpw

#service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-setter
  namespace: jpw
